### ISSUE TITLE
请问游戏的存档在哪，想导出来

### ISSUE THREAD

**Issue by SuSWhW** [Amemei/Cang-LAN-STAR#8]

**Comment by Looading99** [comment]
存档储存在localStorage，如果用edge的话按F12可以查看、修改，但导出不是很方便。

或者：
使用`JSON.stringify(localStorage);"`导出，
使用
var data = JSON.parse("导出的存档");
Object.keys(data).forEach(function (k) {localStorage.setItem(k, data[k]);});
导入。

**Comment by SuSWhW** [comment]
感谢，不过我补了正版，已经通关了
